FROM golang:1.21-alpine AS build

WORKDIR /project

	@@ -10,4 +10,12 @@ COPY . .

RUN go build -o build/fizzbuzz

FROM scratch

WORKDIR /project

COPY --from=build /project/templates templates

COPY --from=build /project/build/fizzbuzz fizzbuzz

CMD ["./fizzbuzz", "serve"]